version: '3.3'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: ${QZ_DATABASE_NAME}
      MYSQL_USER: ${QZ_DATABASE_USER}
      MYSQL_PASSWORD: ${QZ_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${QZ_DATABASE_ROOT_PASSWORD}
    ports:
      - '3306:3306'

#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile_BE
#    container_name: quizzzy-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${QZ_DATABASE_NAME}?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
#      QZ_DATABASE_NAME: ${QZ_DATABASE_NAME}
#      QZ_DATABASE_USER: ${QZ_DATABASE_USER}
#      QZ_DATABASE_PASSWORD: ${QZ_DATABASE_PASSWORD}
#      QZ_DATABASE_ROOT_PASSWORD: ${QZ_DATABASE_ROOT_PASSWORD}
#      JWT_SECRET: ${JWT_SECRET}
#    depends_on:
#      - "mysql"
#    volumes:
#      - ./target/quizzzy-0.0.1-SNAPSHOT.jar:/jar/app.jar



